server:
  port: 8080
  
zookeeper:
  address: 192.168.240.15\:2181,192.168.240.15\:2182,192.168.240.15\:2183
  
spring:
  application:
    name: distributed-seckill
  session:
    store-type: none
  kafka:
    bootstrap-servers:
    - 192.168.240.42:9092
    - 192.168.240.43:9092
    - 192.168.240.44:9092
    consumer:
      group-id: 0
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      batch-size: 65536
      buffer-memory: 524288
  redis:
    database: 0
    port: 6379
    password: dXzMHN2MaHUX
    timeout: 0
    host: 192.168.240.36
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
  datasource:
    write:
      url: jdbc:mysql://192.168.240.29:8096/bm_market?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      username: BlueMoon
      password: bm.mall.123
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 20
      initial-size: 1
      min-idle: 3
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
    read:
      url: jdbc:mysql://192.168.240.29:8096/bm_market?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      username: BlueMoon
      password: bm.mall.123
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 20
      initial-size: 1
      min-idle: 3
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
    
mybatis:
  config-location:  classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  
